# pyproject.toml
[tool.poetry]
name = "tradingview-webhook"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3.3"
hypercorn = "^0.16.0"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
